rootProject.name = 'verdict'

include 'verdict-x509'
include 'verdict-typed'
include 'verdict-authority'
include 'verdict-authority-oci'

include 'digital-assets'
include 'digital-assets:verdict-evm'
include 'digital-assets:verdict-bitcoin'
include 'digital-assets:verdict-tron'
include 'digital-assets:verdict-solana'
include 'digital-assets:verdict-xrp'

include 'agentic-payments'
include 'agentic-payments:verdict-payments'
include 'agentic-payments:verdict-ap2'
include 'agentic-payments:verdict-mc-vi'
