dependencies {
    api project(':')

    api platform('org.exploit.signet:bom:0.1.0')
    api 'org.exploit.signet:solana'

    testRuntimeOnly 'org.exploit:tss4j-natives:1.0.0:linux-amd64@jar'
    testRuntimeOnly 'org.exploit:tss4j-natives:1.0.0:macos-aarch64@jar'
    testRuntimeOnly 'org.exploit:tss4j-natives:1.0.0:windows-amd64@jar'
}

tasks.withType(Test).configureEach {
    jvmArgs '--enable-native-access=ALL-UNNAMED'
}
